Create atoms components
ChristiancChavez/galery-chrisans pull request #7
Opened 2022-07-22 00:42 UTC by ChristiancChavez

2022-07-22 23:17 UTC, jlmonroy13 requested changes

2022-07-22 23:17 UTC, jlmonroy13 commented on src/components/atoms/Dropdown.tsx
>  type selectTypes = {
No estoy seguro de esto pero donde trabajo los `type` comienzan en mayuscula, es decir, `SelectTypes`

2022-07-22 23:17 UTC, jlmonroy13 commented on src/components/atoms/Paragraph.tsx
> +type paragraphTypes = {
mayuscula

2022-07-22 23:17 UTC, jlmonroy13 commented on src/components/atoms/Paragraph.tsx
> +    </span>
return implicito si no vas a tener codigo js entre el const y el return

2022-07-23 23:55 UTC, ChristiancChavez commented on src/components/atoms/Dropdown.tsx
>  type selectTypes = {
Si, ya revise la documentación y si son en mayúsculas.

2022-07-24 01:34 UTC, ChristiancChavez commented on src/components/atoms/Paragraph.tsx
> +type paragraphTypes = {
si ya los cambie

2022-07-24 01:36 UTC, ChristiancChavez commented on src/components/atoms/Paragraph.tsx
> +    </span>
listo, los cambio

2022-07-26 12:57 UTC, jlmonroy13 commented on src/components/atoms/Paragraph.tsx
> +    </span>
Porque si el componente es un parrafo utilizas un span?

2022-07-27 15:27 UTC, andresfch23 approved these changes

2022-07-28 01:01 UTC, jlmonroy13 approved these changes

2022-07-28 01:24 UTC, jlmonroy13 approved these changes

2022-07-28 01:38 UTC, andresfch23 approved these changes

2022-07-28 01:46 UTC, merged